### ISSUE TITLE
OpenGL request

### ISSUE THREAD

**Issue by TimSC** [Habitats/uni#1]
I created some OpenGL examples that were based on your code. It's here: https://github.com/TimSC/py-modern-opengl 

Are you OK for me to release the results under the BSD license?

**Comment by Habitats** [comment]
Sure dude! Do whatever you want. 

I think it's super cool that you even found this!:D

**Comment by TimSC** [comment]
Thanks!

Yeah I stumbled into it on stack exchange :)

**Comment by Habitats** [comment]
Really? Got the link?:P

**Comment by TimSC** [comment]
https://stackoverflow.com/questions/12758570/pyopengl-passing-transformation-matrix-into-shader

**Comment by Habitats** [comment]
Cool!
